first piece of scat
end up with

armlink --scatter="xen.scat"      /home/xtfs/DEV/xen-arm-ds6/xen/common/symbols-dummy.o -o /home/xtfs/DEV/xen-arm-ds6/xen/xen-syms
Error: L6630E: Invalid token start expected number or ( but found < at position 27 on line 32
Error: L6629E: Unmatched parentheses expecting ) but found 1 at position 29 on line 32
"xen.scat", line 32 (column 32): Error: L6228E: Expected '{', found ')...'.
"xen.scat", line 32 (column 32): Error: L6228E: Expected '}', found 'EOF'.

because armlink does not understand shift left expressions